import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Layout from "../../components/Layout";
import List from "../../components/content/list";

const ListContent = () => {
    const router = useRouter();
    const { slug } = router.query;

    return (
        <Layout>
            <Head>
                <title>Blog</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <List slug={slug} />
        </Layout>
    );
};

export default ListContent;
