import type { NextPage } from "next";
import styled from "styled-components";
import Head from "next/head";

import Layout from "../components/Layout";
import { useState } from "react";
import IndexList from "../components/content/indexList";

const AppWrapper = styled.section`
    width: 100%;
    display: flex;
    flex-direction: row;
`;

const checkInnerWidth = (): number => {
    return window.innerWidth;
};

const Home: NextPage = () => {
    return (
        <Layout>
            <Head>
                <title>Blog</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <IndexList />
        </Layout>
    );
};

export default Home;
