import type { NextPage } from "next";
import styled from "styled-components";
import Head from "next/head";
import Image from "next/image";

import { Provider } from "react-redux";
import store from "../redux/store";

import Layout from "../components/Layout";
import Aside from "../components/global/aside";
import Content from "../components/content/content";
import Header from "../components/global/header";
import Footer from "../components/global/footer";
import { useEffect, useLayoutEffect, useState } from "react";

const AppWrapper = styled.section`
    width: 100%;
    display: flex;
    flex-direction: row;
`;

const checkInnerWidth = (): number => {
    return window.innerWidth;
};

const Home: NextPage = () => {
    const [innerWidth, setInnerWidth] = useState(0);

    useLayoutEffect(() => {}, []);

    return (
        <Layout>
            <Head>
                <title>Blog</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </Layout>
    );
};

export default Home;
